#!/bin/zsh

mkdir -p /tmp/updator
echo "AvdanOS Updator request at $(date)" > /tmp/updator/request.avupd

if [[ $EUID -ne 0 ]];
then
    echo "Not running as root. Authorization required\n"
    exec pkexec --disable-internal-agent "$0" "$@"
fi

if [[ "$(realpath /proc/$PPID/exe)" == "/usr/bin/cutefish-settings" ]]; then
export UPD_GUI=1
else
    echo "Warning! You're not running this in Settings application,
    and may run into issues while updating your installation.
    It's highly recommended to run updater inside Settings."
fi

export OS_CURR_VER=$(pacman -Q avdanos_base_image | cut -d " " -f 2)
echo "OS_CURR_VER=\"${OS_CURR_VER}\"" >> /tmp/updator/request.avupd

    if [ -n $(export | grep ARCHISO)]; then
        export OS_WARNING="OS Updates unsupported in Installer image. To try it out, please install AvdanOS on your device."
    fi

# Start by checking for updates
# Make sure to not run pacman -Sy again when updates are already queued. That saves a lot of time.
    export OS_UPD_VAR="/tmp/ready_for_update"
    if [ -e "$OS_UPD_VAR"  ]; then
        echo "Starting update..."
        sudo pacman -S --noconfirm avdanos_base_image $(avdanos_base_image | grep Depends | cut -d ':' -f 2 | sed 's/None//g')
    else
        echo "Checking for updates...
        "
        sudo pacman -Sy | grep "we're doing a quiet update"
        export UPD_AVAIL=$(pacman -Qu | grep -e avdanos_base_image)
    fi

# Check if it's all up to date.
    if [ -n "$UPD_AVAIL" ]; then
        export OS_VER_NEW=$(pacman -Qu avdanos_base_image | cut -d " " -f 4)
        CHANGELOG_CURR=$(curl -s https://avd-cdn.thevakhovske.pw/0:/os_upd/changelog_${OS_CURR_VER})
        CHANGELOG_NEW=$(curl -s https://avd-cdn.thevakhovske.pw/0:/os_upd/changelog_${OS_VER_NEW})
        touch /tmp/ready_for_update
        echo "UPD_AVAIL=\"${UPD_AVAIL}\"" >> /tmp/updator/request.avupd
        echo "OS_VER_NEW=\"${OS_VER_NEW}\"" >> /tmp/updator/request.avupd
        echo "CHANGELOG_CURR=\"${CHANGELOG_CURR}\"" >> /tmp/updator/request.avupd
        echo "CHANGELOG_NEW=\"${CHANGELOG_NEW}\"" >> /tmp/updator/request.avupd
        # Make sure to differentiate between running in settings and terminal emulator
        if [ "$UPD_GUI" = "1" ]; then
            touch /tmp/report_in_settings
        else
            echo "AvdanOS Update available"
            echo "Current version: $OS_CURR_VER"
            echo "New version: $OS_VER_NEW
            "
            echo "Changelog: $CHANGELOG_NEW"
        fi
    elif [ -e "$OS_UPD_VAR"  ]; then
        echo "Update Complete."
        rm /tmp/ready_for_update
    else
        touch /tmp/up_to_date
        CHANGELOG_CURR=$(curl -s https://avd-cdn.thevakhovske.pw/0:/os_upd/changelog_${OS_CURR_VER})
        echo "UP_TO_DATE=\"1\"" >> /tmp/updator/request.avupd
        echo "CHANGELOG_CURR=\"${CHANGELOG_CURR}\"" >> /tmp/updator/request.avupd
        # Make sure to differentiate between running in settings and terminal emulator
        if [ "$UPD_GUI" = "1" ]; then
            touch /tmp/report_in_settings
        else
            echo "AvdanOS Up to date"
            echo "Current version: $OS_CURR_VER
            "
            echo "Current changelog: $CHANGELOG_CURR"
        fi
    fi
